=== solvedata/magento2-plugin/etc/solvedata_events.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="solvedata_events" type="solvedata_events" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="solvedata_events">
        <xs:sequence>
            <xs:element name="event" type="event" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="event">
        <xs:sequence>
            <xs:element name="mutation" type="mutation" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="mutation">
        <xs:attribute name="order" type="xs:string" use="optional" />
        <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== solvedata/magento2-plugin/etc/solvedata_events.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="solvedata_events.xsd">
    <solvedata_events>
        <event name="customer_register_success">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CustomerRegisterSuccess"/>
        </event>
        <event name="customer_account_edited">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CustomerAccountEdited"/>
        </event>
        <event name="customer_address_save_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CustomerAddressSaveAfter"/>
        </event>
        <event name="customer_login">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CustomerLogin"/>
        </event>
        <event name="customer_logout">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CustomerLogout"/>
        </event>
        <event name="checkout_cart_save_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CheckoutCartSaveAfter\CreateOrUpdateCustomer"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CheckoutCartSaveAfter\CreateOrUpdateCart"/>
        </event>
        <event name="newsletter_subscriber_save_commit_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\NewsletterSubscriberSaveCommitAfter"/>
        </event>

        <!-- Order events -->

        <event name="sales_order_save_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\RegisterCustomerForOrder"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CreateOrUpdateOrder"/>

            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\SalesOrderSaveAfter\ConvertCart"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\SalesOrderSaveAfter\CreateOrUpdatePayment"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\SalesOrderSaveAfter\CreateOrUpdateReturn"/>
        </event>
        <event name="sales_order_shipment_save_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\RegisterCustomerForOrder"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CreateOrUpdateOrder"/>
        </event>
        <event name="order_cancel_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\RegisterCustomerForOrder"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\CreateOrUpdateOrder"/>
        </event>
        <event name="sales_quote_merge_after">
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\SalesQuoteMergeAfter\CreateOrUpdateDestinationQuote"/>
            <mutation class="SolveData\Events\Model\Event\Transport\Adapter\GraphQL\Mutation\SalesQuoteMergeAfter\CreateOrUpdateSourceQuote"/>
        </event>
    </solvedata_events>
</config>
